media:
  - name: website_images
    label: Website-Fotos
    input: assets/images
    output: /assets/images
    categories: [image]
    extensions: [jpg, jpeg, png, webp]
    rename: safe

settings:
  hide: true
  content:
    merge: true

content:
  - name: photos
    label: Fotos ändern
    type: group
    items:
      - name: homepage_photos
        label: Startseite
        type: file
        path: content/homepage.json
        format: json
        operations: { create: false, rename: false, delete: false }
        fields:
          - name: hero
            label: Titelbilder
            type: object
            fields:
              - name: summer_image
                label: Sommerfoto
                type: image
                options: { media: website_images }
              - name: winter_image
                label: Winterfoto
                type: image
                options: { media: website_images }

      - name: chalet_4_photos
        label: 4-Zimmer Chalet
        type: file
        path: content/chalet-4.json
        format: json
        operations: { create: false, rename: false, delete: false }
        fields:
          - name: gallery
            label: Fotogalerie
            type: image
            options:
              media: website_images
              multiple: true
              unique: true

      - name: chalet_5_photos
        label: 5-Zimmer Chalet
        type: file
        path: content/chalet-5.json
        format: json
        operations: { create: false, rename: false, delete: false }
        fields:
          - name: gallery
            label: Fotogalerie
            type: image
            options:
              media: website_images
              multiple: true
              unique: true

      - name: location_photos
        label: Lage & Anfahrt
        type: file
        path: content/location.json
        format: json
        operations: { create: false, rename: false, delete: false }
        fields:
          - name: slope_image
            label: Foto direkt an der Piste
            type: image
            options: { media: website_images }
