/* Public content bridge. It deliberately accepts only content records and runs
 * before the protected page scripts, so a Decap edit cannot alter layout or JS. */
(() => {
  const page=(location.pathname.split('/').pop()||'index.html').replace('.html','')||'index';
  const slug={index:'home','chalet-4-zimmer':'chalet-4','chalet-5-zimmer':'chalet-5'}[page]||page;
  const get=path=>{try{const request=new XMLHttpRequest();request.open('GET',path,false);request.send(null);return request.status>=200&&request.status<300?JSON.parse(request.responseText):null}catch{return null}};
  const global=get('content/global.json')||{},data=get(`content/${slug}.json`)||{};
  window.acCmsPageData=data;window.acCmsGlobal=global;
  window.acCmsHero=(id,fallback)=>{const hero=(data.heroes||[]).find(item=>item.id===id);return hero?.image||fallback};
  window.acCmsGallery=(id,fallback=[])=>{const gallery=(data.galleries||[]).find(item=>item.id===id);const images=(gallery?.images||[]).map(item=>typeof item==='string'?item:item.image).filter(Boolean);return images.length?images:fallback};
  const safe=value=>String(value||'').replace(/<(?!br\s*\/?\s*>)/gi,'&lt;').replace(/<\/(?!br\s*>)/gi,'&lt;/');
  window.acCmsTranslations={de:{},en:{}};
  for(const item of data.translations||[]){window.acCmsTranslations.de[item.id]=item.de;window.acCmsTranslations.en[item.id]=item.en}
  const setText=(el,value)=>{const field=el.querySelector('input,select,textarea');if(el.tagName==='LABEL'&&field){let node=[...el.childNodes].find(child=>child.nodeType===Node.TEXT_NODE);if(!node){node=document.createTextNode('');el.insertBefore(node,field)}node.textContent=value.replace(/<br\s*\/?\s*>/gi,' ');return}el.innerHTML=value};
  for(const item of data.texts||[]){const el=document.querySelector(`[data-cms-text="${CSS.escape(item.id)}"]`);if(!el)continue;el.dataset.de=safe(item.de);el.dataset.en=safe(item.en);const active=localStorage.getItem('alpenchalets-language')==='en'?'en':'de';setText(el,el.dataset[active]||el.dataset.de||'')}
  for(const item of data.media||[]){const el=document.querySelector(`[data-cms-media="${CSS.escape(item.id)}"]`);if(!el||!item.image)continue;el.setAttribute(el.dataset.cmsAttr||'src',item.image)}
  for(const item of data.links||[]){const el=document.querySelector(`[data-cms-url="${CSS.escape(item.id)}"]`);if(el&&item.url)el.href=item.url}
  document.querySelectorAll('[data-cms-gallery]').forEach(host=>{const gallery=(data.galleries||[]).find(item=>item.id===host.dataset.cmsGallery);if(!gallery?.images?.length)return;const images=gallery.images.map(item=>typeof item==='string'?item:item.image).filter(Boolean);if(host.matches('.detail-gallery'))host.innerHTML=images.map(image=>`<button class="gallery-item" data-src="${image}"><img loading="lazy" decoding="async" src="${image}" alt="Chalet"></button>`).join('');});
  const faqHost=document.querySelector('.faq .legal');if(faqHost&&(data.faqs||[]).length){faqHost.querySelectorAll('details').forEach(item=>item.remove());for(const item of data.faqs){const detail=document.createElement('details'),summary=document.createElement('summary'),answer=document.createElement('p');summary.dataset.de=safe(item.question_de);summary.dataset.en=safe(item.question_en);summary.innerHTML=summary.dataset[localStorage.getItem('alpenchalets-language')==='en'?'en':'de'];answer.dataset.de=safe(item.answer_de);answer.dataset.en=safe(item.answer_en);answer.innerHTML=answer.dataset[localStorage.getItem('alpenchalets-language')==='en'?'en':'de'];detail.append(summary,answer);faqHost.append(detail)}}
  document.querySelectorAll('[data-cms-carousel]').forEach(host=>{const gallery=(data.galleries||[]).find(item=>item.id===host.dataset.cmsCarousel);if(!gallery?.floorplan||!gallery?.images?.length)return;const slides=host.querySelector('.chalet-carousel-slides');if(!slides)return;const images=gallery.images.map(item=>typeof item==='string'?item:item.image).filter(Boolean);slides.innerHTML=`<figure class="is-active is-floorplan"><img loading="lazy" decoding="async" src="${gallery.floorplan}" alt="Grundriss"></figure>`+images.map(image=>`<figure><img loading="lazy" decoding="async" src="${image}" alt="Chalet"></figure>`).join('');const count=host.querySelector('.chalet-carousel-count');if(count)count.textContent=`1 / ${images.length+1}`;});
  document.querySelectorAll('a[href^="tel:"]').forEach(el=>{el.href=`tel:${(global.contact?.phone||'').replace(/[^+\d]/g,'')}`;el.textContent=global.contact?.phone||el.textContent});
  document.querySelectorAll('a[href^="mailto:"]').forEach(el=>{el.href=`mailto:${global.contact?.email||''}`;el.textContent=global.contact?.email||el.textContent});
})();
